root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "builds/main"
include_ext = ["go"]
log = "air.log"

[log]
time = true
main_only = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
