services:
  api:
    build:
      dockerfile: ./Dockerfile.dev
    env_file:
        - .env.dev
    ports:
      - "${ILET_API_LISTEN_PORT}:${ILET_API_LISTEN_PORT}"
      - "${ILET_ROUTER_LISTEN_PORT}:${ILET_ROUTER_LISTEN_PORT}"
    volumes:
      - ./:/app  
    restart: always
    depends_on: 
      - db

  db:
    image: postgres:16.4-alpine3.20
    restart: always
    env_file:
        - .env.dev
